version: '3.8'

services:
  # 1. MOTORE DI CALCOLO (Python)
  engine:
    build: ./engine
    ports:
      - "8000:8000"
    volumes:
      - ./engine:/app
    networks:
      - quidsi-net

  # 2. DATABASE (MongoDB)
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - quidsi-net

  # 3. BACKEND/MIDDLEWARE (Node.js)
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - engine
      - database
    environment:
      - PYTHON_URL=http://engine:8000
      - MONGO_URL=mongodb://database:27017/quidsi
    networks:
      - quidsi-net

  # 4. FRONTEND (Vue.js)
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - quidsi-net

networks:
  quidsi-net:
    driver: bridge

volumes:
  mongo-data: