version: '3.8'

services:
  # 1. IL MOTORE PYTHON
  engine:
    build: ./engine
    ports:
      - "8000:8000"
    volumes:
      - ./engine:/app # Così se modifichi il codice si aggiorna
    networks:
      - quidsi-net

  # 2. IL SERVER NODE
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - engine
    environment:
      # IMPORTANTE: Qui diciamo a Node che Python non è su "localhost" ma su "engine"
      - PYTHON_URL=http://engine:8000
    networks:
      - quidsi-net

  # 3. IL CLIENT VUE
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Serve per l'hot-reload su Windows
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - quidsi-net

networks:
  quidsi-net:
    driver: bridge